### ISSUE TITLE
修复配置页面

### ISSUE THREAD

**Issue by BroKun** [difizen/magent#33]
- [x] prompt反的
- [x] 大模型设置无法做

- [x] 知识
- [x] 工具 by @lulusir 
- [x] 并没有更新配置
- [x] 要求一般prompt量级比较大，应该展示大一点

开场白在其他地方处理。
更新配置目前报错

**Comment by lulusir** [comment]
认领

- [ ] prompt反的
- [ ] 大模型设置无法做
- [ ] 开场白没展示出来
- [ ] 知识、工具都没展示出来
- [ ] 并没有更新配置
- [ ] 要求一般prompt量级比较大，应该展示大一点
